version: '1'
services:
  webapp:

    # Give your image a static name
    image: prometheus_microservice_image:v1.0

    # Give your container a static name
    container_name: prometheus_microservice_container

    build:
      context: .
      args:
          requirements: ./requirements.txt   

      #dockerfile: .\DockerFile

    entrypoint: python wsgi.py

    # Env file
    env_file:
      - .env

    ports:
     - "5000:5000"
    links:
     - mongo
    depends_on:
     - mongo


  mongo:
    image: "mongo:latest"

    # Give your container a static name
    container_name: mongo_container

    ports:
     - "27017:27017"

    command: mongod --port 27017 --bind_ip 0.0.0.0